server:
  port: ${XYZ:15000}
spring:
  application:
    name: customer-aggregator
  cloud:
   loadbalancer:
      retry:
        max-retries-on-next-service-instance: 2
        max-retries-on-same-service-instance: 0
        retry-on-all-operations: true
  config:
    import: configserver:http://127.0.0.1:8888
  security:
    user:
      name: user
      password: 123456
resilience4j:
  retry:
    instances:
      customer-int-add-customer-retry:
        base-config: base1
        retry-exception-predicate: org.training.capital.microservice.mscustomeraggregator.integration.retry.MyRetryPredicate
        result-predicate: org.training.capital.microservice.mscustomeraggregator.integration.retry.MyResultPredicate
      customer-int-rollback-customer-retry:
        base-config: base1
    configs:
      base1:
        max-attempts: 3
        wait-duration: 100ms
        exponential-backoff-multiplier: 3
        exponential-max-wait-duration: 1s
        enable-exponential-backoff: false
  circuitbreaker:
    instances:
      customer-int-add-customer-cb:
        sliding-window-type: count_based
        sliding-window-size: 20
        minimum-number-of-calls: 10
        failure-rate-threshold: 30
        wait-duration-in-open-state: 5s
        automatic-transition-from-open-to-half-open-enabled: false
        permitted-number-of-calls-in-half-open-state: 10
        slow-call-duration-threshold: 500ms
        slow-call-rate-threshold: 50
user:
  login:
    info:
      user-infos:
      - username: osman
        password: ENC(LZ17e8aEk3VnEH4WJ0kiKf3oGPSPzdFOT3J/xaQ+oLEkaTmnf63WuIUozEDKreHJ)
        role: ADMIN
      - username: ali
        password: ENC(LZ17e8aEk3VnEH4WJ0kiKf3oGPSPzdFOT3J/xaQ+oLEkaTmnf63WuIUozEDKreHJ)
        role: USER
