server:
  port: ${xyz:8080}
spring:
  application:
    name: apigw-order
  config:
    import: configserver:http://127.0.0.1:8888
  cloud:
    gateway:
      routes:
        - id: route1
          uri: lb://ORDER
          predicates:
            - Path=/apigw/api/v1/order/**
            - TokenCheck=true, osman
          filters:
            - RewritePath=/apigw/?(?<segment>.*), /$\{segment}
            - Logging=debug, osman